# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diego Charrez 
full_name: Diego David Charrez Ticona 
email: dcharrezt@gmail.com
email2: dcharrezt@unsa.edu.pe
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dcharrezt.github.io" # the base hostname & protocol for your site
github_username:  dcharrezt
twitter_username: dcharrezt
linkedin_username: dcharrezt
# stackoverflow: 6802703/dcharrezt
include: ['_pages']
# stackexchange: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
